print("Commands")
print("Help                  Displays this, Duh")
print("Sysfetch              Fetches Device Info")
print("Echo                  Prints text into the Terminal")
print("Ls                    Lists the contents of the current directory")
print("SPT Install           Installs a Package from either an offical ShellOS Repo or a Custom Link ")
print("SPT Uninstall         Uninstalls a Package")
print("Networkstatus         Tells you if you're connected to a network and connection type")
print("RM                    Removes an item")
print("MK                    Makes an item")
print("CD                    Changes Directory")
print("Time                  Returns the current time")
print("Date                  Returns current date")